version: '3.8'

services:
  master:
    image: postgres:15
    container_name: pg_master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dio
      POSTGRES_DB: mydb
      # Gunakan PGDATA default
    ports:
      - "5434:5432"
    volumes:
      - master_data:/var/lib/postgresql/data
      - ./master/init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
    command: >
      postgres -c wal_level=replica
               -c max_wal_senders=10
               -c max_replication_slots=10
               -c hot_standby=on
               -c archive_mode=on
               -c archive_command='cp %p /var/lib/postgresql/data/archive/%f'
               -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  replica:
    image: postgres:15
    container_name: pg_replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dio
      POSTGRES_DB: mydb
      # Gunakan PGDATA default
    ports:
      - "5435:5432"
    depends_on:
      master:
        condition: service_healthy
    volumes:
      - replica_data:/var/lib/postgresql/data
      - ./replica/setup-replica.sh:/setup-replica.sh
    entrypoint: ["/bin/bash", "/setup-replica.sh"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  master_data:
    name: pg_master_data
  replica_data:
    name: pg_replica_data
